# Data Validity Testing

### Imports and Notebook Settings

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os 
import re
from pathlib import Path

In [3]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
# import seaborn as sns 
import plotly.express as px
import pprint

In [4]:
ROOT = Path.cwd().parent

In [5]:
style_path = ( ROOT 
              / 'notebooks' 
              / 'styler.mplstyle'
              )
plt.style.use(style_path)

## GDELT Articles

### Records

In [15]:
data_path = (
    ROOT
    / "data"
    / "silver"
    / "source=gdelt"
    / "records.parquet"
)

df = pd.read_parquet(data_path)

In [16]:
df.columns

Index(['record_id', 'source', 'source_type', 'title', 'text', 'published_at',
       'retrieved_at', 'url', 'region', 'categories', 'metadata', 'raw'],
      dtype='object')

In [17]:
len(df)

50839

In [9]:
df.head()

,record_id,source,source_type,title,text,published_at,retrieved_at,url,region,categories,metadata,raw
0,miso:1d177eec150969381dad79e56fe8c26a128a2de3e...,miso_notifications,api,[MISO] Real-Time Operations Posting Delay Dela...,"Due to technical difficulties, the MISO daily ...",2025-03-06 08:09:58+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/4a8a979858f246...,MISO,"[market_notice, RealTime]","{'topic': 'RealTime', 'notification_id': 0, 'p...","{'topic': 'RealTime', 'notification': {'notifi..."
1,miso:c8a53d365f7c84658b23907c02328cc6af955ff78...,miso_notifications,api,[MISO] Real-Time Operations Posting Delay Miss...,"Due to technical difficulties, the MISO report...",2025-11-14 11:46:08+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/0872ee2b587747...,MISO,"[market_notice, RealTime]","{'topic': 'RealTime', 'notification_id': 0, 'p...","{'topic': 'RealTime', 'notification': {'notifi..."
2,miso:2fa98689170a01f46ef3008fe3a14c925beb7c7ad...,miso_notifications,api,[MISO] Settlements Misc. Adjustment for 01/24/...,The Capacity Replacement Non-Compliance Charge...,2026-01-20 13:41:56+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/f28e2f56d1104c...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
3,miso:c4367d5a7c82ebfb08fb6ea41b26a35e437cf0769...,miso_notifications,api,[MISO] Settlements - Energy Market Rates for F...,The rates for February 2026 are as follows: • ...,2026-01-28 16:05:58+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/bc44fffe58cd46...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
4,miso:66167fbe9db19b4ae854bb5e6749ff43bcde7e5a1...,miso_notifications,api,[MISO] Settlements - RLA E1 Statement Updated ...,MISO has republished the RLA E1 statements tha...,2026-01-29 14:05:00+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/5d61c4e60f314d...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."

In [10]:
df['published_at'].min()

Timestamp('2025-03-06 08:09:58+0000', tz='UTC')

In [14]:
df.sort_values(by=['published_at']).head(20)

,record_id,source,source_type,title,text,published_at,retrieved_at,url,region,categories,metadata,raw
0,miso:1d177eec150969381dad79e56fe8c26a128a2de3e...,miso_notifications,api,[MISO] Real-Time Operations Posting Delay Dela...,"Due to technical difficulties, the MISO daily ...",2025-03-06 08:09:58+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/4a8a979858f246...,MISO,"[market_notice, RealTime]","{'topic': 'RealTime', 'notification_id': 0, 'p...","{'topic': 'RealTime', 'notification': {'notifi..."
1,miso:c8a53d365f7c84658b23907c02328cc6af955ff78...,miso_notifications,api,[MISO] Real-Time Operations Posting Delay Miss...,"Due to technical difficulties, the MISO report...",2025-11-14 11:46:08+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/0872ee2b587747...,MISO,"[market_notice, RealTime]","{'topic': 'RealTime', 'notification_id': 0, 'p...","{'topic': 'RealTime', 'notification': {'notifi..."
2,miso:2fa98689170a01f46ef3008fe3a14c925beb7c7ad...,miso_notifications,api,[MISO] Settlements Misc. Adjustment for 01/24/...,The Capacity Replacement Non-Compliance Charge...,2026-01-20 13:41:56+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/f28e2f56d1104c...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
3,miso:c4367d5a7c82ebfb08fb6ea41b26a35e437cf0769...,miso_notifications,api,[MISO] Settlements - Energy Market Rates for F...,The rates for February 2026 are as follows: • ...,2026-01-28 16:05:58+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/bc44fffe58cd46...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
4,miso:66167fbe9db19b4ae854bb5e6749ff43bcde7e5a1...,miso_notifications,api,[MISO] Settlements - RLA E1 Statement Updated ...,MISO has republished the RLA E1 statements tha...,2026-01-29 14:05:00+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/5d61c4e60f314d...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
5,miso:cc1436f0c8828a8936d2d53bcbd5bb598096a7951...,miso_notifications,api,[MISO] Market Settlements Summer 2025 MO Non-P...,Summer 2025 Must Offer Non-Performance charges...,2026-02-04 10:22:27+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/4dd91d429fcb48...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
6,miso:9589dc56ae43e6e189ddbd1763982a5c4bd8790c5...,miso_notifications,api,[MISO] Market Settlements Upcoming Resettlements,We would like to inform market participants of...,2026-02-13 11:11:27+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/fe3969da25a84f...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
7,miso:78aa600fbc1034184ee7282dd507975f65a2a4523...,miso_notifications,api,[MISO] Market Settlements Settlement Statement...,MISO identified and resolved an issue that pre...,2026-02-17 13:43:01+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/cb5c47795b724d...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
8,miso:05b8ac9cd58acb86cbbfdcbefdaf505cf0ef5de1b...,miso_notifications,api,[MISO] Settlements - Monthly EQR Report for Ja...,The monthly EQR data files for January 2026 ha...,2026-02-17 15:37:19+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/f7f126deab2f4b...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
9,miso:0cad51a46fdfabc78411544dc2456a10777f1b725...,miso_notifications,api,[MISO] Market Settlements Demand Response Tool...,The Demand Response Tool has been updated for ...,2026-02-19 12:44:11+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/b10c766b105a43...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
10,miso:da1ed728088041ba6f5f1242faaca1c20b49b5e84...,miso_notifications,api,[MISO] Settlements - Energy Market Rates for M...,The rates for March 2026 are as follows: • FTR...,2026-02-24 13:28:22+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/87610e1c82e84e...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
11,miso:fc2313423fa30e4d65a4c07796a5f68a0dcf4d283...,miso_notifications,api,[MISO] Settlements Misc. Adjustment for 02/26/...,MISO will be processing a RT_MISC in the amoun...,2026-02-26 07:50:03+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/a867333d5d4545...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
12,miso:aa912addbe79ac78e74118bf4cf17851b98dfcd6f...,miso_notifications,api,[MISO] Settlements - Additional CRNCC for Fall...,Resource Adequacy has informed Market Settleme...,2026-03-02 09:26:44+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/7e447f48c92c45...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
13,miso:1731a83c00b27b972a2207dd9f344c40d4f3b10da...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-06 13:57:26+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/c5454df83fc14a...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
14,miso:7c5bc6167a5606d83e27bb748a9f005a8e1dcb223...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-06 14:48:10+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/0dcae11a5aea45...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
15,miso:5f6a517c0f7e3e73c8b3d0d507371626aade785f9...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-06 15:00:23+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/eae677f5fb6d41...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
16,miso:13472df1006451fe65a4640d6793f3598ef92f314...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-10 11:06:21+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/f35daf052a5b49...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
17,miso:337efa8af7fa0a14dbd26a67222f7c91573db3adb...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-10 11:53:31+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/336e9b89e6a948...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
18,miso:36097a58fcd2f4dce10321755a1354b984255fed0...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-10 13:26:18+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/af46595efaae4a...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."
19,miso:76ca375564fbdf8a769c5829d5e52a5ad9a998a09...,miso_notifications,api,[MISO] Settlements - System Wide EEEF for Oper...,MISO has granted a System-Wide Excessive Energ...,2026-03-10 14:27:40+00:00,2026-07-24 16:55:35.429987+00:00,https://www.misoenergy.org/link/c833c6fbf6434e...,MISO,"[market_notice, Settlements]","{'topic': 'Settlements', 'notification_id': 0,...","{'topic': 'Settlements', 'notification': {'not..."

In [ ]:
df['metadata'].iloc[0]

In [ ]:
len(df)

In [ ]:
df["url"].isna().mean()

In [ ]:
dup_rate = df["url"].duplicated().mean()
print(f"{dup_rate:.2%}")

In [ ]:
from urllib.parse import urlparse

df["domain"] = df["url"].apply(
    lambda x: urlparse(x).netloc
)

df["domain"].value_counts().head(30)

In [ ]:
df["title"].ne('').mean()

In [ ]:

for i in df['title'].iloc[:25]:
    print(i)

In [ ]:
duplicates = df.loc[(df["title"].duplicated(keep=False)) & (df['title'].str.strip().ne('')) & df["title"].notna()].sort_values("title")
duplicates.loc[:, ['title', 'url']]

In [ ]:
df["title_length"] = (
    df["title"]
    .fillna("")
    .str.len()
)

df["title_length"].describe()

In [ ]:
from collections import Counter
import re

words = []

for title in df["title"].dropna():
    words.extend(
        re.findall(r"\b[a-z]+\b", title.lower())
    )

Counter(words).most_common(50)

In [ ]:
df.iloc[0]["categories"]

In [ ]:
df.iloc[0]["metadata"]

In [ ]:
sample = df.sample(
    100,
    random_state=42
)

In [ ]:
sample[
    ["title", "url"]
].to_csv(
    "gdelt_review.csv",
    index=False
)

In [ ]:
daily_counts = (
    df.groupby(
        pd.to_datetime(df["published_at"]).dt.date
    )
    .size()
)

In [ ]:
plt.figure(figsize=(8, 5))
daily_counts.plot()

plt.ylabel('Article Counts')

In [ ]:
from collections import Counter
import json

org_counter = Counter()

for metadata in df["metadata"].dropna():
    try:
        data = json.loads(metadata) if isinstance(metadata, str) else metadata

        organizations = data.get("organizations", [])

        if organizations:
            org_counter.update(organizations)

    except Exception:
        continue

top_orgs = (
    pd.DataFrame(
        org_counter.most_common(50),
        columns=["organization", "count"]
    )
)

print(top_orgs)

### Scraped Articles

In [ ]:
data_path = (
    ROOT
    / "data"
    / "silver"
    / "source=gdelt"
    / "articles.parquet"
)

df = pd.read_parquet(data_path)

In [ ]:
df.columns

In [ ]:
df['metadata'].iloc[0]

In [ ]:
df["has_precise_published_at"] = df["metadata"].apply(
    lambda x: x.get("has_precise_published_at", False)
)
df["precise_published_at_source"] = df["metadata"].apply(
    lambda x: x.get("published_at_source", None)
)

In [ ]:
df[['published_at', 'has_precise_published_at', 'precise_published_at_source']]

In [ ]:
df["has_precise_published_at"].mean()

In [ ]:
df.loc[df['has_precise_published_at'], 'precise_published_at_source'].value_counts()

In [ ]:
df['published_at'].min()

In [ ]:
df['published_at'].max()

In [ ]:
df.info()

In [ ]:
(
    df["success"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

In [ ]:
(
    (df["scrape_status"].value_counts() / len(df))
    .mul(100)
    .round(2)
)

In [ ]:
(
    df.groupby("error_type")
      .size()
      .sort_values(ascending=False)
)

In [ ]:
(
    df.groupby("status_code")
      .size()
      .sort_values(ascending=False)
)

In [ ]:
df["text_length"].describe()

In [ ]:
from urllib.parse import urlparse

df["domain"] = (
    df["url"]
    .apply(lambda x: urlparse(x).netloc)
)

In [ ]:
(
    df.groupby("domain")["success"]
      .mean()
      .sort_values()
)

In [ ]:
(
    df.groupby("domain")
      .size()
      .sort_values(ascending=False)
      .head(30)
)

In [ ]:
sample = (
    df[df["success"]]
    .sample(50, random_state=42)
)

In [ ]:
sample['text']

## IEM AFOS

In [ ]:
data_path = (
    ROOT
    / "data"
    / "silver"
    / "source=iem_afos"
    / "records.parquet"
)

df = pd.read_parquet(data_path)

In [ ]:
df.columns

In [ ]:
len(df)

In [ ]:
df.iloc[0]

In [ ]:
df.columns

In [ ]:
df["metadata"].iloc[20]

In [ ]:
df["source"].value_counts()

In [ ]:
df["product_type"] = df["metadata"].apply(
    lambda x: x.get("product_type")
)

df["product_type"].value_counts()

In [ ]:
df["region"].value_counts()

In [ ]:
(
    df.groupby(
        [
            pd.to_datetime(df["published_at"]).dt.date,
            "region"
        ]
    )
    .size()
    .unstack(fill_value=0)
)

In [ ]:
df["text_length"] = (
    df["text"]
    .fillna("")
    .str.len()
)

(
    df.groupby("product_type")["text_length"]
      .describe()
)

In [ ]:
weather_terms = [
    "snow",
    "ice",
    "lake effect",
    "thunderstorm",
    "tornado",
    "wind",
    "heat",
    "cold",
    "rain",
    "flood"
]

for term in weather_terms:
    count = (
        df["text"]
        .str.lower()
        .str.contains(term, na=False)
        .sum()
    )

    print(term, count)

In [ ]:
winter_terms = (
    df["text"]
    .str.lower()
    .str.contains(
        "snow|ice|blizzard|freezing",
        regex=True,
        na=False,
    )
)

summer_terms = (
    df["text"]
    .str.lower()
    .str.contains(
        "heat|thunderstorm",
        regex=True,
        na=False,
    )
)

In [ ]:
monthly = (
    df.assign(
        winter=winter_terms,
        summer=summer_terms,
        month=pd.to_datetime(df["published_at"]).dt.month,
    )
    .groupby("month")[["winter", "summer"]]
    .mean()
)

print(monthly)

In [ ]:
import matplotlib.pyplot as plt

monthly.plot(
    kind="bar",
    figsize=(10, 5),
)

plt.title("AFOS Weather Term Frequency by Month")
plt.ylabel("Record Count")
plt.xlabel("Month")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()