# EIA Numeric Data

### Imports and Notebook Settings

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os 
import re
from pathlib import Path

In [3]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
# import seaborn as sns 
import pprint 

from datetime import datetime, timezone

In [4]:
from dotenv import load_dotenv


from eml_transformer.sources.numeric.eia930.region import (
    EIA930RegionSource
)
from eml_transformer.sources.numeric.eia930.interchange import (
    EIA930InterchangeSource
)

In [5]:
ROOT = Path.cwd().parent

In [6]:
style_path = ( ROOT 
              / 'notebooks' 
              / 'styler.mplstyle'
              )
plt.style.use(style_path)

In [7]:
FROM_DATE = datetime(2026, 8, 1, tzinfo=timezone.utc)
TO_DATE = datetime(2026, 8, 2, tzinfo=timezone.utc)

In [8]:
source = EIA930RegionSource()

records = list(
    source.fetch_records(
        from_date=FROM_DATE,
        to_date=TO_DATE,
    )
)

print("Bronze records:", len(records))

if records:
    pprint.pprint(records[0])

Bronze records: 81
BronzeRecord(source='eia930_region',
             record_id='eia930_region:MISO:D:2026-08-01T00',
             published_at=datetime.datetime(2026, 8, 1, 0, 0, tzinfo=datetime.timezone.utc),
             retrieved_at=datetime.datetime(2026, 8, 12, 21, 27, 1, 918559, tzinfo=datetime.timezone.utc),
             raw={'period': '2026-08-01T00',
                  'respondent': 'MISO',
                  'respondent-name': 'Midcontinent Independent System '
                                     'Operator, Inc.',
                  'type': 'D',
                  'type-name': 'Demand',
                  'value': '98695',
                  'value-units': 'megawatthours'})

In [9]:
rows = []
for i in list(records): 
    record = source.standardize_record(i)
    rows.append(record)

region_df = pd.DataFrame(rows)

In [10]:
region_df

,record_id,source,observed_at,variable,value,retrieved_at,region,unit,dimensions,metadata
0,eia930_region:MISO:D:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,actual_load,98695.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
1,eia930_region:MISO:DF:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,load_forecast,103464.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
2,eia930_region:MISO:NG:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,net_generation,98748.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
3,eia930_region:MISO:TI:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,total_interchange,-2449.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
4,eia930_region:MISO:D:2026-08-01T01,eia930_region,2026-08-01 01:00:00+00:00,actual_load,96222.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
...,...,...,...,...,...,...,...,...,...,...
76,eia930_region:MISO:DF:2026-08-01T23,eia930_region,2026-08-01 23:00:00+00:00,load_forecast,97365.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
77,eia930_region:MISO:NG:2026-08-01T23,eia930_region,2026-08-01 23:00:00+00:00,net_generation,101381.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
78,eia930_region:MISO:D:2026-08-02T00,eia930_region,2026-08-02 00:00:00+00:00,actual_load,94521.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
79,eia930_region:MISO:DF:2026-08-02T00,eia930_region,2026-08-02 00:00:00+00:00,load_forecast,96017.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
80,eia930_region:MISO:NG:2026-08-02T00,eia930_region,2026-08-02 00:00:00+00:00,net_generation,98748.0,2026-08-12 21:27:01.918559+00:00,MISO,MWh,"{'respondent': 'MISO', 'measurement_type': 'D'}","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."

### Interchange

In [11]:
source = EIA930InterchangeSource()

records = list(
    source.fetch_records(
        from_date=FROM_DATE,
        to_date=TO_DATE,
    )
)

print("Bronze records:", len(records))

if records:
    pprint.pprint(records[0])

Bronze records: 390
BronzeRecord(source='eia930_interchange',
             record_id='eia930_interchange:MISO:AECI:2026-08-01T06',
             published_at=datetime.datetime(2026, 8, 1, 6, 0, tzinfo=datetime.timezone.utc),
             retrieved_at=datetime.datetime(2026, 8, 12, 21, 27, 3, 245457, tzinfo=datetime.timezone.utc),
             raw={'fromba': 'MISO',
                  'fromba-name': 'Midcontinent Independent System Operator, '
                                 'Inc.',
                  'period': '2026-08-01T06',
                  'toba': 'AECI',
                  'toba-name': 'Associated Electric Cooperative, Inc.',
                  'value': '-37',
                  'value-units': 'megawatthours'})

In [12]:
rows = []
for i in list(records): 
    record = source.standardize_record(i)
    rows.append(record)

interchange_df = pd.DataFrame(rows)

In [13]:
interchange_df

,record_id,source,observed_at,variable,value,retrieved_at,region,unit,dimensions,metadata
0,eia930_interchange:MISO:AECI:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-37.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Midcontinent Independent Syst...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
1,eia930_interchange:MISO:IESO:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-676.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Midcontinent Independent Syst...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
2,eia930_interchange:MISO:LGEE:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,342.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Midcontinent Independent Syst...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
3,eia930_interchange:MISO:MHEB:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-2370.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Midcontinent Independent Syst...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
4,eia930_interchange:MISO:PJM:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-3087.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Midcontinent Independent Syst...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
...,...,...,...,...,...,...,...,...,...,...
385,eia930_interchange:SIKE:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,17.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Sikeston Board of Municipal U...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
386,eia930_interchange:SOCO:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,938.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,"{'from_region': 'Southern Company Services, In...","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
387,eia930_interchange:SPA:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,325.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,{'from_region': 'Southwestern Power Administra...,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
388,eia930_interchange:SWPP:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,-138.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,"{'from_region': 'Southwest Power Pool', 'to_re...","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
389,eia930_interchange:TVA:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,-1821.0,2026-08-12 21:27:03.245457+00:00,MISO,MWh,"{'from_region': 'Tennessee Valley Authority', ...","{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."

In [14]:
from eml_transformer.features.builder import *

In [15]:
DATA_PATH = ROOT / 'data' / 'silver' / 'source=eia930_region' / 'artifact=records'
df = pd.read_parquet(DATA_PATH)


eia_region_df = build_eia_region_daily(df)

In [16]:
eia_region_df.head()

,observed_at,load_mean,load_min,load_max,generation_total
0,2019-01-01 00:00:00+00:00,66921.625000,61045.0,74304.0,1486931.0
1,2019-01-02 00:00:00+00:00,73749.041667,63330.0,81731.0,1624549.0
2,2019-01-03 00:00:00+00:00,76128.500000,67706.0,84464.0,1720260.0
3,2019-01-04 00:00:00+00:00,75005.375000,67258.0,81557.0,1692936.0
4,2019-01-05 00:00:00+00:00,69994.791667,64439.0,78404.0,1567645.0

In [17]:
len(eia_region_df)

2770

In [18]:
DATA_PATH = ROOT / 'data' / 'silver' / 'source=eia930_interchange' / 'artifact=records'
df = pd.read_parquet(DATA_PATH)


eia_interchange_df = build_eia_interchange_features(df)

In [19]:
eia_interchange_df.head()

                observed_at region  total_imports_lag_24  total_exports_lag_24
0 2025-01-01 00:00:00+00:00   MISO                   NaN                   NaN
1 2025-01-01 01:00:00+00:00   MISO                   NaN                   NaN
2 2025-01-01 02:00:00+00:00   MISO                   NaN                   NaN
3 2025-01-01 03:00:00+00:00   MISO                   NaN                   NaN
4 2025-01-01 04:00:00+00:00   MISO                   NaN                   NaN

In [20]:
len(eia_interchange_df)

14070

In [21]:
DATA_PATH = ROOT / 'data' / 'silver' / 'source=eia930_region' / 'artifact=records'
df = pd.read_parquet(DATA_PATH)


eia_interchange_hourly_df = build_eia_region_hourly(df)

In [22]:
eia_interchange_hourly_df.head()

,observed_at,region,actual_load,load_forecast,net_generation,total_interchange,observed_at_eta,actual_load_lag_1,actual_load_lag_24,actual_load_lag_168,hour,day_of_week,day_name,day_type,month,is_weekend,is_holiday
0,2019-01-01 00:00:00+00:00,MISO,74304.0,81595.0,70466.0,-5676.0,2018-12-31 19:00:00-05:00,NaN,NaN,NaN,0,1,Tuesday,weekday,1,False,False
1,2019-01-01 01:00:00+00:00,MISO,73391.0,80484.0,69693.0,-5428.0,2018-12-31 20:00:00-05:00,74304.0,NaN,NaN,1,1,Tuesday,weekday,1,False,False
2,2019-01-01 02:00:00+00:00,MISO,71531.0,78470.0,67805.0,-5231.0,2018-12-31 21:00:00-05:00,73391.0,NaN,NaN,2,1,Tuesday,weekday,1,False,False
3,2019-01-01 03:00:00+00:00,MISO,69562.0,76301.0,66177.0,-4940.0,2018-12-31 22:00:00-05:00,71531.0,NaN,NaN,3,1,Tuesday,weekday,1,False,False
4,2019-01-01 04:00:00+00:00,MISO,67744.0,73623.0,64142.0,-5035.0,2018-12-31 23:00:00-05:00,69562.0,NaN,NaN,4,1,Tuesday,weekday,1,False,False

In [23]:
len(eia_interchange_hourly_df)

66457

In [27]:
DATA_PATH = ROOT / 'data' / 'gold' / 'datasets' / 'dataset=load_forecasting'
df = pd.read_parquet(DATA_PATH)

In [28]:
df.dropna()

,observed_at,region,actual_load,load_forecast,net_generation,total_interchange,observed_at_eta,actual_load_lag_1,actual_load_lag_24,actual_load_lag_168,hour,day_of_week,day_name,day_type,month,is_weekend,is_holiday,total_imports_lag_24,total_exports_lag_24
52632,2025-01-02 00:00:00+00:00,MISO,76148.0,76258.0,73091.0,-4590.0,2025-01-01 19:00:00-05:00,72869.0,75428.0,67501.0,0,3,Thursday,weekday,1,0,0,3574.0,-2241.0
52633,2025-01-02 01:00:00+00:00,MISO,76735.0,77162.0,73657.0,-4609.0,2025-01-01 20:00:00-05:00,76148.0,74692.0,67317.0,1,3,Thursday,weekday,1,0,0,3449.0,-2293.0
52634,2025-01-02 02:00:00+00:00,MISO,76245.0,76891.0,73501.0,-4222.0,2025-01-01 21:00:00-05:00,76735.0,72895.0,66792.0,2,3,Thursday,weekday,1,0,0,2564.0,-2208.0
52635,2025-01-02 03:00:00+00:00,MISO,75154.0,76123.0,72762.0,-3761.0,2025-01-01 22:00:00-05:00,76245.0,71047.0,66102.0,3,3,Thursday,weekday,1,0,0,1934.0,-2245.0
52636,2025-01-02 04:00:00+00:00,MISO,73732.0,74231.0,70663.0,-4322.0,2025-01-01 23:00:00-05:00,75154.0,69819.0,65136.0,4,3,Thursday,weekday,1,0,0,1345.0,-2612.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66452,2026-07-31 20:00:00+00:00,MISO,103003.0,106141.0,103309.0,-2322.0,2026-07-31 16:00:00-04:00,102471.0,111335.0,96102.0,20,4,Friday,weekday,7,0,0,824.0,-1846.0
66453,2026-07-31 21:00:00+00:00,MISO,103125.0,106814.0,103154.0,-2487.0,2026-07-31 17:00:00-04:00,103003.0,113220.0,97294.0,21,4,Friday,weekday,7,0,0,1132.0,-2370.0
66454,2026-07-31 22:00:00+00:00,MISO,102409.0,106965.0,102564.0,-2242.0,2026-07-31 18:00:00-04:00,103125.0,113542.0,97944.0,22,4,Friday,weekday,7,0,0,1099.0,-2998.0
66455,2026-07-31 23:00:00+00:00,MISO,100899.0,105986.0,101381.0,-2052.0,2026-07-31 19:00:00-04:00,102409.0,112633.0,97933.0,23,4,Friday,weekday,7,0,0,298.0,-3111.0
66456,2026-08-01 00:00:00+00:00,MISO,98695.0,103464.0,98748.0,-2449.0,2026-07-31 20:00:00-04:00,100899.0,110992.0,96469.0,0,5,Saturday,weekend,8,1,0,875.0,-4915.0