# EIA Numeric Data

### Imports and Notebook Settings

In [22]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
import os 
import re
from pathlib import Path

In [24]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
# import seaborn as sns 
import pprint 

from datetime import datetime, timezone

In [25]:
from dotenv import load_dotenv


from eml_transformer.sources.numeric.eia930.region import (
    EIA930RegionSource
)
from eml_transformer.sources.numeric.eia930.interchange import (
    EIA930InterchangeSource
)

In [26]:
ROOT = Path.cwd().parent

In [27]:
style_path = ( ROOT 
              / 'notebooks' 
              / 'styler.mplstyle'
              )
plt.style.use(style_path)

In [28]:
FROM_DATE = datetime(2026, 8, 1, tzinfo=timezone.utc)
TO_DATE = datetime(2026, 8, 2, tzinfo=timezone.utc)

In [29]:
source = EIA930RegionSource()

records = list(
    source.fetch_records(
        from_date=FROM_DATE,
        to_date=TO_DATE,
    )
)

print("Bronze records:", len(records))

if records:
    pprint.pprint(records[0])

Bronze records: 81
BronzeRecord(source='eia930_region',
             record_id='eia930_region:MISO:D:2026-08-01T00',
             published_at=datetime.datetime(2026, 8, 1, 0, 0, tzinfo=datetime.timezone.utc),
             retrieved_at=datetime.datetime(2026, 8, 4, 15, 59, 50, 888247, tzinfo=datetime.timezone.utc),
             raw={'period': '2026-08-01T00',
                  'respondent': 'MISO',
                  'respondent-name': 'Midcontinent Independent System '
                                     'Operator, Inc.',
                  'type': 'D',
                  'type-name': 'Demand',
                  'value': '98695',
                  'value-units': 'megawatthours'})

In [30]:
rows = []
for i in list(records): 
    record = source.standardize_record(i)
    rows.append(record)

region_df = pd.DataFrame(rows)

In [31]:
region_df

,record_id,source,observed_at,variable,value,retrieved_at,region,unit,metadata
0,eia930_region:MISO:D:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,actual_load,98695.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
1,eia930_region:MISO:DF:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,load_forecast,103464.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
2,eia930_region:MISO:NG:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,net_generation,98748.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
3,eia930_region:MISO:TI:2026-08-01T00,eia930_region,2026-08-01 00:00:00+00:00,total_interchange,-2449.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
4,eia930_region:MISO:D:2026-08-01T01,eia930_region,2026-08-01 01:00:00+00:00,actual_load,96222.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
...,...,...,...,...,...,...,...,...,...
76,eia930_region:MISO:DF:2026-08-01T23,eia930_region,2026-08-01 23:00:00+00:00,load_forecast,97365.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
77,eia930_region:MISO:NG:2026-08-01T23,eia930_region,2026-08-01 23:00:00+00:00,net_generation,101381.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
78,eia930_region:MISO:D:2026-08-02T00,eia930_region,2026-08-02 00:00:00+00:00,actual_load,94521.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
79,eia930_region:MISO:DF:2026-08-02T00,eia930_region,2026-08-02 00:00:00+00:00,load_forecast,96017.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
80,eia930_region:MISO:NG:2026-08-02T00,eia930_region,2026-08-02 00:00:00+00:00,net_generation,98748.0,2026-08-04 15:59:50.888247+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."

### Interchange

In [32]:
source = EIA930InterchangeSource()

records = list(
    source.fetch_records(
        from_date=FROM_DATE,
        to_date=TO_DATE,
    )
)

print("Bronze records:", len(records))

if records:
    pprint.pprint(records[0])

Bronze records: 390
BronzeRecord(source='eia930_interchange',
             record_id='eia930_interchange:MISO:AECI:2026-08-01T06',
             published_at=datetime.datetime(2026, 8, 1, 6, 0, tzinfo=datetime.timezone.utc),
             retrieved_at=datetime.datetime(2026, 8, 4, 15, 59, 51, 375785, tzinfo=datetime.timezone.utc),
             raw={'fromba': 'MISO',
                  'fromba-name': 'Midcontinent Independent System Operator, '
                                 'Inc.',
                  'period': '2026-08-01T06',
                  'toba': 'AECI',
                  'toba-name': 'Associated Electric Cooperative, Inc.',
                  'value': '-37',
                  'value-units': 'megawatthours'})

In [33]:
rows = []
for i in list(records): 
    record = source.standardize_record(i)
    rows.append(record)

interchange_df = pd.DataFrame(rows)

In [34]:
interchange_df

,record_id,source,observed_at,variable,value,retrieved_at,region,unit,metadata
0,eia930_interchange:MISO:AECI:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-37.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
1,eia930_interchange:MISO:IESO:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-676.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
2,eia930_interchange:MISO:LGEE:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,342.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
3,eia930_interchange:MISO:MHEB:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-2370.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
4,eia930_interchange:MISO:PJM:2026-08-01T06,eia930_interchange,2026-08-01 06:00:00+00:00,interchange,-3087.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
...,...,...,...,...,...,...,...,...,...
385,eia930_interchange:SIKE:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,17.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
386,eia930_interchange:SOCO:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,937.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
387,eia930_interchange:SPA:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,325.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
388,eia930_interchange:SWPP:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,-138.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."
389,eia930_interchange:TVA:MISO:2026-08-02T00,eia930_interchange,2026-08-02 00:00:00+00:00,interchange,-1821.0,2026-08-04 15:59:51.375785+00:00,MISO,MWh,"{'provider': 'EIA', 'dataset': 'EIA-930', 'rou..."